<a href="https://colab.research.google.com/github/chaitsugale/GENAI_STUDY_MATERIAL/blob/main/sentence_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

In [2]:
import torch

In [3]:
from transformers import BertTokenizer,BertModel

In [4]:
import random

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
random_seed = 42

In [7]:
random.seed(random_seed)

In [8]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(random_seed)

In [9]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [10]:
model = BertModel.from_pretrained("bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [13]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [27]:
text = "ineuron is for the best AI Courses."
text2 = "with great power comes great responsibilities"

In [28]:
#tokenizer --> encode the text and provide attention mask
encoding = tokenizer.batch_encode_plus([text,text2],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [29]:
input_ids = encoding["input_ids"]

In [34]:
input_ids

tensor([[  101,  1999, 11236,  2239,  2003,  2005,  1996,  2190,  9932,  5352,
          1012,   102],
        [  101,  2007,  2307,  2373,  3310,  2307, 10198,   102,     0,     0,
             0,     0]])

In [30]:
attention_mask = encoding["attention_mask"]

In [35]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]])

In [31]:
with torch.no_grad():
  outputs = model(input_ids=input_ids,attention_mask=attention_mask)
  word_embeddings = outputs.last_hidden_state

In [32]:
word_embeddings.shape

torch.Size([2, 12, 768])

In [33]:
word_embeddings

tensor([[[-0.4271, -0.1666,  0.1909,  ..., -0.2987,  0.6356,  0.6963],
         [-0.4555, -0.5843,  0.3312,  ..., -0.1475,  0.5605,  1.2290],
         [-0.7174, -0.4126,  1.0531,  ...,  0.3063,  0.3983,  0.2660],
         ...,
         [ 0.3224,  0.1035,  0.5626,  ..., -0.2507, -0.0866, -0.3084],
         [ 0.5164,  0.1578, -0.0727,  ...,  0.2103, -0.4651, -0.2494],
         [ 0.2963,  0.2963,  0.2604,  ...,  0.3185, -0.6820, -0.1199]],

        [[-0.1470,  0.4077, -0.3124,  ..., -0.5304,  0.1688,  0.2320],
         [-0.3841,  0.0955,  0.3607,  ..., -0.4388,  0.1090,  0.3216],
         [ 0.1086, -0.0538,  0.1405,  ..., -0.4991, -0.4260, -0.2317],
         ...,
         [-0.1574, -0.3009,  0.0105,  ...,  0.2512, -0.0191, -0.2138],
         [-0.0909, -0.2267,  0.0512,  ...,  0.3157, -0.0699, -0.1929],
         [-0.2577, -0.3732,  0.0036,  ...,  0.1789,  0.0662, -0.1593]]])

In [36]:
input_ids[0][0]

tensor(101)

In [39]:
decode = tokenizer.decode(input_ids[1],skip_special_tokens =True)

In [40]:
decode

'with great power comes great responsibilities'